### ISSUE TITLE
Why doesn't adding overlapSize not increasing the total number of embeddings/chunks?

### ISSUE THREAD

**Issue by LexiestLeszek** [ZachNagengast/similarity-search-kit#13]
So I experiment with the chunk sizes and decided to use overlapSize. But what I encountered is that no matter whether I add it or not, it doesn't change anything in my search results nor in the total number of embeddings. 

I use this code inside my ContentView (the one that was adviced in one of the previous issues on how to change chunksSize):             
            let splitter = RecursiveTokenSplitter(withTokenizer: BertTokenizer())
            let (splitText, _) = splitter.split(text: documentText, chunkSize: 200, overlapSize: 100)
            chunks = splitText

**Comment by ZachNagengast** [comment]
For recursive token splitter, it doesn't actually use overlap size in the algorithm, it just has it there to conform to the protocol.  It would be possible to do this ad-hoc since the chunk tokens are also returned as the second part of the tuple.

**Comment by LexiestLeszek** [comment]
What do you mean ad-hoc? Sorry, im just starting out and don't understand what you mean.

**Comment by ZachNagengast** [comment]
Ad-hoc as in after the fact. Since splitText is an array, you could loop through the array and add some portion of the text from the end of the previous chunk to the start of the next chunk.

The reason it's not changing the total number of embeddings is because RecursiveTokenSplitter is setup to specifically get as close to the chunkSize without going over, so either way - overlapSize won't impact your total, only changes in chunkSize will affect this.

**Comment by LexiestLeszek** [comment]
I added an overlapping functionality and it seems to be working:

            let overlapSize = 50
            let splitter = RecursiveTokenSplitter(withTokenizer: BertTokenizer())
            let (splitText, _) = splitter.split(text: documentText, chunkSize: 300, overlapSize: overlapSize)
            
            chunks = splitText
            embeddings = []
            
            for i in 0..<splitText.count {
                let previousChunk = i > 0 ? splitText[i-1].suffix(overlapSize) : ""
                let currentChunk = splitText[i]
                
                let chunkWithOverlap = previousChunk + currentChunk
                chunks.append(String(chunkWithOverlap))
            }

**Comment by ZachNagengast** [comment]
Resolved with #14

**Comment by longseespace** [comment]
Noob question but it doesn't seem to work. I tried with multiple chunk sizes and overlap size but it never produce the correct answer like when I use with `RecursiveTokenSplitter`

Here is the warning I got when using `RecursiveCharacterSplitter`, chunksize 1000, overlapSize 200.

```
Input sentence is too long 9430 > 512, truncating.
```

A similarity search always gives 0 search results.

**Comment by LexiestLeszek** [comment]
As far as I'm concerned, the embeddings model is 512 tokens long, so each chunk cannot exceed this limit anyways.

**Comment by ZachNagengast** [comment]
Yea, something seems suspicious about that large 9430 number, but the chunk size should definitely be a max of 510 since the model requires 2 tokens for the input and can only accept 512 total.
