### ISSUE TITLE
How can you cluster together similar documents?

### ISSUE THREAD

**Issue by henrypratt** [ZachNagengast/similarity-search-kit#18]
I noticed that is one of the features listed in the readme, but I have not been able to find any documentation or examples of clustering documents.

**Comment by ZachNagengast** [comment]
Clustering as a feature isn't included right now in this library, however, it does make it easy for you to do this using your own code to do this, once you have a similarity index of all your documents. You can use an algorithm like t-SNE or UMAP to do this, based on all the vectors you've generated, more info here: https://www.pinecone.io/learn/k-means-clustering/

**Comment by henrypratt** [comment]
Thanks for the response. Is it possible to get the vector of a sentence? Since it is not possible to apply k-means clustering to an array of euclidean distances.

**Comment by ZachNagengast** [comment]
Yep! The `encode` function in the embeddings classes returns a float vector: https://github.com/ZachNagengast/similarity-search-kit#embeddingprotocol

**Comment by henrypratt** [comment]
Thank you!
