### ISSUE TITLE
Gracefully throw exception instead of using fatalError

### ISSUE THREAD

**Issue by longseespace** [ZachNagengast/similarity-search-kit#19]
Hi. I think as a library, SSK should gracefully throw an exception and let the application handle it instead of crashing the app.

What do you think? @ZachNagengast 

https://github.com/ZachNagengast/similarity-search-kit/blob/d591adc15ebadfdc43f1fd63fc62863478f9b970/Sources/SimilaritySearchKit/Core/Index/SimilarityIndex.swift#L119

**Comment by ZachNagengast** [comment]
Yes very much agreed.

It would be great to know why this is failing if you have any more debug info. 

https://github.com/ZachNagengast/similarity-search-kit/blob/d591adc15ebadfdc43f1fd63fc62863478f9b970/Sources/SimilaritySearchKit/Core/Index/SimilarityIndex.swift#L115-L121

In the meantime, this can definitely fail more quietly.

**Comment by ZachNagengast** [comment]
@longseespace this should be addressed in release 0.0.9 https://github.com/ZachNagengast/similarity-search-kit/releases/tag/0.0.9 but definitely lmk if you get anymore info about why the setupDimension is failing sometimes.
