### ISSUE TITLE
Disk indexing coming?

### ISSUE THREAD

**Issue by aehlke** [ZachNagengast/similarity-search-kit#21]
Is disk storage for the indexes planned, or is it fast enough to use that the indexes can be built on every app launch?

**Comment by ZachNagengast** [comment]
Thanks to this PR you can save and load indexes on disk already https://github.com/ZachNagengast/similarity-search-kit/pull/16

**Comment by ZachNagengast** [comment]
There's a few different options such as json or binary https://github.com/ZachNagengast/similarity-search-kit/tree/main/Sources/SimilaritySearchKit/Core/Persistence

**Comment by aehlke** [comment]
Amazing thank you

While I'm here - it looks like this lib also needs upgrading to be able to support the new iOS 17 NLContextualEmbedding, is that correct? https://www.wwdcnotes.com/notes/wwdc23/10042/

**Comment by ZachNagengast** [comment]
Yep, there's a good example of some code using it in this repo https://github.com/apple/ml-stable-diffusion/commit/7f9c58a6c1483a6da1f398cad49eee2f9fa3bee4#diff-fadaa8d2dd21c410a4f9ef64b9fa090799b8a2814bc6851408b3b29cf4f920a4

**Comment by aehlke** [comment]
Thank you, I've seen this one example plus a couple articles in Japanese that discuss the code. However what I can't make sense of is how to go from having the contextual embeddings, to using them in a similarity search.

Do you plan to add this new API to this library? If so I'd just adopt the current embeddings options and offer the iOS 17 feature to capable devices later on. I'd help add it but don't understand how to generalize beyond using it as an input for SD. Thanks

**Comment by ZachNagengast** [comment]
I have a draft of this API that I'm hoping to finish up soon, FYI

**Comment by aehlke** [comment]
FWIW I'm also now waiting for USearch to add text similarity search around end of this month, which is usable from Swift as well as WASM/others. Then I plan to use it with NLContextualEmbedding on iOS/mac, or something else for web deployment via SwiftWASM.

**Comment by ZachNagengast** [comment]
I just pushed #22 as a PR, if you can check it out and let me know how it works for you that would be helpful!

**Comment by ZachNagengast** [comment]
Merged #22 into main which contains this new embedding class.
