### ISSUE TITLE
Exception in ChatWithFilesExample

### ISSUE THREAD

**Issue by gerasimsergey** [ZachNagengast/similarity-search-kit#26]
`2023-11-08 15:02:34.693989+0200 ChatWithFilesExample[17397:4904410] [espresso] [Espresso::handle_ex_plan] exception=Espresso exception: "Invalid state": inner product kernel p.has_biases is true, but biases were not found! [Exception from Layer: 14: x_1_cast]
2023-11-08 15:02:34.694158+0200 ChatWithFilesExample[17397:4904410] [coreml] Error computing NN outputs -1
2023-11-08 15:02:34.694214+0200 ChatWithFilesExample[17397:4904410] [coreml] Failure in -executePlan:error:.
Failed to generate query embedding for 'hello'.`

macOS 10.3.1 Xcode Version 14.3.1 (14E300c)

**Comment by ZachNagengast** [comment]
@gerasimsergey You'll need at least macOS 13 to build everything properly, sorry about that!

**Comment by gerasimsergey** [comment]
Sorry I made a mistake
I use 13.3.1

help me please  @ZachNagengast

**Comment by ZachNagengast** [comment]
@gerasimsergey Can you update your Xcode to the latest as well and try again?
