### ISSUE TITLE
How to add CamemBERT?

### ISSUE THREAD

**Issue by juliencampy** [ZachNagengast/similarity-search-kit#27]
Hi there,

I am using your framework successfully with the included models, it's great!
However most of the documents my app will have to process are in French, so I was wondering if CamemBERT could be used?
https://huggingface.co/camembert/camembert-large

I tried converting it to mlpackage using your scripts or https://github.com/huggingface/exporters, but failed.

Is it even possible?

Thanks a lot.

**Comment by ZachNagengast** [comment]
Hi @juliencampy what exactly was the issue you were seeing, was it during conversion or was it after importing it as an `EmbeddingsProtocol`?

**Comment by ZachNagengast** [comment]
Closing this for now but lmk what the issue you're seeing is and I can help with the conversion. Thanks!
